import { MusicTrack, ShopItem } from "@/lib/models"

export const seedMusicTracks: MusicTrack[] = [
  {
    id: "neon-dreams",
    title: "NEON DREAMS",
    duration: "3:24",
    imageUrl: "/placeholder.svg?height=300&width=300",
    streams: 45000,
    spotifyUrl: "https://spotify.com/track/neon-dreams",
    appleMusicUrl: "https://music.apple.com/track/neon-dreams",
    priceCents: 129,
    active: true,
  },
  {
    id: "midnight-vibes",
    title: "MIDNIGHT VIBES",
    duration: "2:58",
    imageUrl: "/placeholder.svg?height=300&width=300",
    streams: 32000,
    spotifyUrl: "https://spotify.com/track/midnight-vibes",
    appleMusicUrl: "https://music.apple.com/track/midnight-vibes",
    priceCents: 129,
    active: true,
  },
  {
    id: "golden-hour",
    title: "GOLDEN HOUR",
    duration: "4:12",
    imageUrl: "/placeholder.svg?height=300&width=300",
    streams: 67000,
    spotifyUrl: "https://spotify.com/track/golden-hour",
    appleMusicUrl: "https://music.apple.com/track/golden-hour",
    priceCents: 129,
    active: true,
  },
  {
    id: "electric-soul",
    title: "ELECTRIC SOUL",
    duration: "3:45",
    imageUrl: "/placeholder.svg?height=300&width=300",
    streams: 54000,
    spotifyUrl: "https://spotify.com/track/electric-soul",
    appleMusicUrl: "https://music.apple.com/track/electric-soul",
    priceCents: 129,
    active: true,
  },
]

export const seedShopItems: ShopItem[] = [
  {
    id: "pink-paradise-set",
    title: "PINK PARADISE SET",
    category: "glam",
    priceCents: 4599,
    imageUrl: "/placeholder.svg?height=400&width=300",
    isGrwm: false,
    active: true,
  },
  {
    id: "streetwear-sunday",
    title: "STREETWEAR SUNDAY",
    category: "grwm",
    priceCents: 0,
    imageUrl: "/placeholder.svg?height=400&width=300",
    isGrwm: true,
    videoUrl: "https://youtube.com",
    active: true,
  },
  {
    id: "neon-dreams-crop",
    title: "NEON DREAMS CROP",
    category: "casual",
    priceCents: 3299,
    imageUrl: "/placeholder.svg?height=400&width=300",
    isGrwm: false,
    active: true,
  },
  {
    id: "date-night-glam",
    title: "DATE NIGHT GLAM",
    category: "grwm",
    priceCents: 0,
    imageUrl: "/placeholder.svg?height=400&width=300",
    isGrwm: true,
    videoUrl: "https://youtube.com",
    active: true,
  },
]
